Include CPEs and fix golang purls
kubernetes-sigs/bom pull request #173
Opened 2022-10-07 17:35 UTC by sbs2001

Fix https://github.com/kubernetes-sigs/bom/issues/169
https://github.com/kubernetes-sigs/bom/issues/142

Adds syft as dep to provide CPEs for now. This is temporary and we want to use something else as discussed with @puerco .

2022-10-07 17:40 UTC, cpanato commented
/assign @puerco 

we need to review this, I personally would not like to have syft as dependency here

2022-10-11 22:40 UTC, puerco requested changes
Thanks for this @sbs2001 
We do need to generate CPEs for go modules. But this PR is pulling all of syft as a dependency for achieve. We need to implement our own CPE logic or find a specialized library that will do that for us.

2022-10-11 22:40 UTC, puerco commented on go.mod
> +	github.com/anchore/syft v0.58.0
OK, not like this. This is pulling the whole syft project as a dependency.

2022-10-23 15:23 UTC, sbs2001 commented
@puerco  this PR now only fixes https://github.com/kubernetes-sigs/bom/issues/169

2022-10-30 05:29 UTC, puerco commented
/ok-to-test

2022-10-30 05:33 UTC, puerco commented
Thanks @sbs2001 Sorry I was (am) traveling and I missed the last updates to this PR. It LGTM in general but it seems the linter is not happy. Also, could you add a simple unit test to ensure we don't miss this one again?

Thanks!

2022-10-30 07:03 UTC, sbs2001 commented
@puerco  I'll make changes later this week or next week (I have exams rn)

2022-10-30 13:13 UTC, puerco commented
No rush, if i can I'll try to push the linter fixes into your branch to help out!

2022-11-04 12:09 UTC, sbs2001 commented
@puerco  linter is fixed and test is added

2022-11-05 21:57 UTC, puerco approved these changes
Thanks @sbs2001 !
/lgtm

2022-11-05 21:58 UTC, merged